###
POST http://localhost:3333/messages
Content-Type: application/json

{
    "jid": "558781204523@s.whatsapp.net",
    "message": {
        "text": "Ola mundo"
    }
}
###
GET http://localhost:3333/messages
Content-Type: application/json

###
GET http://localhost:3333/messages/00214C3847CAB449946B84931D9FAF84
Accept: image/jpeg
